[workspace]
members = ["atomic-enum-derive"]

[package]
name = "atomic-enum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-enum-derive = { path="./atomic-enum-derive" }
